### ISSUE TITLE
`screen.debug()` spits out a very long JS Object instead of a web component

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#16]
Repro:

* Download and unzip this project: [shadow-dom-testing-library repro.zip](https://github.com/KonnorRogers/shadow-dom-testing-library/files/9904686/shadow-dom-testing-library.repro.zip)
* Run `npm ci` to install dependencies
* Run `npm run test` to run the tests. See the output of the `screen.debug()` log is hundreds of thousands of lines of nested JS objects rather than the HTML.
* Open `babel.config.js` There's a comment there explaining one way that the issue can be toggled on/off.

Summary for those who don't want to do the steps above: Jest by default uses Babel to transform the code. If no targets are specified, Babel will transform the code to the oldest possible versions. It seems that when doing so the code is transformed in such a way that the problem is "fixed". If the target is any ES6+ version, then the problem is present. This is why a simple sandbox isn't enough to reproduce it since it will transform it to ES5 by default.

In addition, even if this did work, it doesn't show any contents of the shadow DOM which makes it hard to know which queries to use from this library.

**Comment by KonnorRogers** [comment]
Thanks! I have a repro of this as well using Vitest! Tracking this along with #17
