### ISSUE TITLE
Queries suggest replacements incorrectly

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#26]
Currently the `queryAllBy` methods in this library have `suggest = false` so that Testing Library doesn't attempt to suggest better queries. It'd be nice if the suggestions could work with this library but that's another issue. The current issue is that all of the other queries (`getBy`, `getAllBy`, `queryBy`, `findBy`, `findAllBy`) still will suggest incorrectly when used.

It seems like this is because `buildQueries` will wrap the shadow queries [like this](https://github.com/testing-library/dom-testing-library/blob/bb79e3027df4e10f04bf10a13bf5a8f85723e876/src/query-helpers.ts#L232) which results in a check for suggestions before your method sets it to false.

It seems like a solution would be to wrap every query similar to how you are doing it [here](https://github.com/KonnorRogers/shadow-dom-testing-library/blob/a9a3482111f28e8ed3844c52fdf98574c388803e/src/shadow-queries.ts#L64-L68).

**Comment by KonnorRogers** [comment]
Closed by #29
