### ISSUE TITLE
`deepQuerySelector` and `deepQuerySelectorAll` are not exported

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#30]
The README lists additional APIs `deepQuerySelector` and `deepQuerySelectorAll` [here](https://github.com/konnorrogers/shadow-dom-testing-library#additional-apis) but those don't seem to be exported.

This would be very useful as an escape hatch when we need a raw querySelector. Can this be exposed?

**Comment by KonnorRogers** [comment]
Of course! I'll make a v1.6.0 release with these.

**Comment by CreativeTechGuy** [comment]
Thanks!
