### ISSUE TITLE
`screen.debug()` modifies DOM (Schrödinger's DOM)

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#32]
I was experiencing a strange issue where if I had `screen.debug()` in my test, the following steps would behave differently. After some digging, I realized it was because the debug method actually modified the DOM. It appears to be from [these lines](https://github.com/KonnorRogers/shadow-dom-testing-library/blob/main/src/pretty-shadow-dom.ts#L61-L64) where `node` is a reference to the actual DOM and an element is inserted.

Can the node be copied first so that the actual DOM isn't changed as a result of debugging?

**Comment by KonnorRogers** [comment]
DOH! Thanks! Yea a cloneNode should work here.
