### ISSUE TITLE
`deepQuerySelectorAll` doesn't recurse into root container's shadowRoot

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#33]
If the code hits [these lines](https://github.com/KonnorRogers/shadow-dom-testing-library/blob/c5fa6086d91c8b451a5f2fe4e92331efabbfa154/src/deep-query-selectors.ts#L33-L39) it has identified that the container is a shadow root, but it doesn't then look inside of that shadow root. This seems to only be an issue for the initial `container` element.

This results in a wildly different output if `elem` vs `elem.parentElement` is passed. (Given that `elem` is a shadowRoot.) In this example, if `elem` is passed, the result will be `[elem, elem.shadowRoot]` which misses everything that is inside of that shadowRoot.

Related #23

**Comment by KonnorRogers** [comment]
@CreativeTechGuy seems like it would need to run the selector on both the shadow root and the container itself.

**Comment by KonnorRogers** [comment]
I'm starting to question my implementation of `deepQuerySelector` since it seems like it may add some false positives...I may want an extra check for "*" queries so it doesn't give false positives.

**Comment by KonnorRogers** [comment]
All this to say, I don't believe its currently acting as a true "querySelector" since its pushing both shadowroots and host elements into the final elements array instead of only returning children of the element. Right now its more of a tree walker than a true querySelector.

**Comment by CreativeTechGuy** [comment]
Related: `deepQuerySelector`, because it returns the first element from `deepQuerySelectorAll` it'll always return the container that was passed in since that'll always be the first element. That should be solved by #36 but I wanted to call out another way in which this issue appears for anyone else struggling with it.
