### ISSUE TITLE
TypeScript - deepQuerySelector returns Element instead of HTMLElement

### ISSUE THREAD

**Issue by CreativeTechGuy** [KonnorRogers/shadow-dom-testing-library#40]
It seems like a bug that [`deepQuerySelector` returns the type `Element`](https://github.com/KonnorRogers/shadow-dom-testing-library/blob/d2a1a2a2624ef6f806714189de28a5443cfeb9a4/src/deep-query-selectors.ts#L3-L7) when [`deepQuerySelectorAll` returns the type `HTMLElement`](https://github.com/KonnorRogers/shadow-dom-testing-library/blob/d2a1a2a2624ef6f806714189de28a5443cfeb9a4/src/deep-query-selectors.ts#L29-L34) by default.

This makes it difficult to pass/use the result of `deepQuerySelector` since it's missing most of the properties that are needed.

Also, is there a reason that `deepQuerySelectorAll` takes a generic for the return type but `deepQuerySelector` does not? It'd make sense if they both did.

**Comment by KonnorRogers** [comment]
No reason. I'll get a fix for this.
