### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by AnimeAllstar** [KonnorRogers/shadow-dom-testing-library#51]
I've been trying to use this library with `jest@26` and `@testing-library/react@12` which supports React 16, but `container.shadowRoot` is always null. Does `@testing-library/react@12` no support shadowDOMs?

I have set `testEnvironment: "jsdom"`, but I haven't installed `jsdom` or `jest-environment-jsdom` separately since I'm using `jest@26` and it is included in `jest`.

**Comment by KonnorRogers** [comment]
@AnimeAllstar Can you tell me what specific version of Jest + JSDOM you're using?

https://shoelace.style/frameworks/react/#upgrade-jest

I wrote those docs on the Shoelace website, specifically you need Jest >= 26.5 and JSDOM >= 16.2.0 to get shadow roots rendering properly in Jest / JSDOM

**Comment by AnimeAllstar** [comment]
@KonnorRogers thanks for the quick response. I am using `jest@26.6.3`. I am not installing `jsdom` manually since I think Jest actually ships with `jsdom` for for `jest@26.6.3`.

**Comment by KonnorRogers** [comment]
@AnimeAllstar The version of `testing-library` _shouldn't_ matter I don't think.

The key component to shadow dom rendering is around `JSDOM`.

I would see if you could upgrade the version of JSDOM if possible to a higher version.

**Comment by KonnorRogers** [comment]
@AnimeAllstar if you have a repo you could share, I'd be happy to take a look.

**Comment by AnimeAllstar** [comment]
Hey @KonnorRogers I think we can close this issue. The issue for me was that I was using this internal component library at our company that required some extra babel config. Thanks for reaching out.

**Comment by KonnorRogers** [comment]
Awesome thanks! If you have hit any other problems feel free to open a new issue, or if it's the same problem, feel free to reopen!
