### ISSUE TITLE
project is missing a license

### ISSUE THREAD

**Issue by markgoho** [KonnorRogers/shadow-dom-testing-library#55]
please add a license (MIT?) so that orgs that need it can use this library appropriately

**Comment by KonnorRogers** [comment]
@markgoho while there's no actual License.txt the package.json at least has a "license" field. I'll work on adding an actual TXT file to the root tho.

https://github.com/KonnorRogers/shadow-dom-testing-library/blob/ea993a3285da0816a5b84507d2c9f9926d4989fe/package.json#L45
